name: e
description: Comprehensive set of tools for working with Euler's number
version: 1.0.0
repository: https://github.com/xooniverse/e

topics: 
  - math
  - eulers
  - number

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
